src/main/java/maven/testecasadocodigo/model/CarrinhoCompras.java
package maven.testecasadocodigo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

@Component
@Scope(value = WebApplicationContext.SCOPE_SESSION, 
proxyMode = ScopedProxyMode.TARGET_CLASS)
public class CarrinhoCompras implements Serializable{

	private Map<CarrinhoItem, Integer> itens = new LinkedHashMap<CarrinhoItem, Integer>();

	public void add(CarrinhoItem item) {
		
		itens.put(item, getQuantidade(item) + 1);
		
		
	}

	public Integer getQuantidade(CarrinhoItem item) {
		if(! itens.containsKey(item)) {
			itens.put(item, 0);
		}
		
		System.out.println(itens.get(item));
		return itens.get(item);
		
	}

	public int getQuantidade() {
		return itens.values().stream().reduce(0, 
				(proximo, acumulador) -> proximo + acumulador);
	}

	public Collection<CarrinhoItem> getItens() {
		return itens.keySet();
	}
	
	public BigDecimal getTotal() {
		BigDecimal total = BigDecimal.ZERO;
		
		for (CarrinhoItem item : itens.keySet()) {
			total = total.add(getTotal(item));
		}
		
		return total;
	}
	
	public BigDecimal getTotal(CarrinhoItem item){
		System.out.println(item);
		return item.getTotal(getQuantidade(item));
		
	}

	public void remover(Integer produtoId, Tipo tipoPreco) {
		Produto produto = new Produto();
		produto.setId(produtoId);
		itens.remove(new CarrinhoItem(produto, tipoPreco));
		
	}

	
	
}

src/main/java/maven/testecasadocodigo/controller/HomeController.java
package maven.testecasadocodigo.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import maven.testecasadocodigo.dao.ProdutoDAO;
import maven.testecasadocodigo.model.Produto;

@Controller
public class HomeController {

	@Autowired
	private ProdutoDAO produtoDAO;
	
	
	@RequestMapping("/")
	@Cacheable(value = "produtoHome")
	public ModelAndView index() {
		List<Produto> produtos =  produtoDAO.listar();
		ModelAndView mav = new ModelAndView("home");
		mav.addObject("produtos", produtos);
		
		return mav;
	}
}

src/main/java/maven/testecasadocodigo/controller/LoginController.java
package maven.testecasadocodigo.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class LoginController {

	@RequestMapping(value="/login", method = RequestMethod.GET)
	public String loginForm() {
		return "loginForm";
	}
}

src/main/webapp/WEB-INF/views/cabecalho.jsp
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
	<header id="layout-header">
		<div class="clearfix container">
			<a href="${s:mvcUrl('HC#index').build() }" id="logo"> </a>
			<div id="header-content">
				<nav id="main-nav">

					<ul class="clearfix">
						<li>
						<a href="${s:mvcUrl('CCC#itens').build() }" rel="nofollow">
						<s:message code="menu.carrinho" 
							arguments="${carrinhoCompras.quantidade }" />
						</a>
						</li>
						
						<li><a href="/pages/sobre-a-casa-do-codigo" rel="nofollow"><fmt:message key="menu.sobre"/></a></li>
						<li><a href="?locale=pt" rel="nofollow"><fmt:message key="menu.pt"/></a></li>
						<li><a href="?locale=en_US" rel="nofollow"><fmt:message key="menu.en"/></a></li>
		
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<nav class="categories-nav">
		<ul class="container">
			<li class="category"><a href="http://www.casadocodigo.com.br">Home</a></li>
			<li class="category"><a href="/collections/livros-de-agile">
					<fmt:message key="navegacao.categoria.agile"/> </a></li>
			<li class="category"><a href="/collections/livros-de-front-end">
					<fmt:message key="navegacao.categoria.front_end"/> </a></li>
			<li class="category"><a href="/collections/livros-de-games">
					<fmt:message key="navegacao.categoria.games"/> </a></li>
			<li class="category"><a href="/collections/livros-de-java">
					<fmt:message key="navegacao.categoria.java"/> </a></li>
			<li class="category"><a href="/collections/livros-de-mobile">
					<fmt:message key="navegacao.categoria.mobile"/> </a></li>
			<li class="category"><a
				href="/collections/livros-desenvolvimento-web"> <fmt:message key="navegacao.categoria.web"/> </a></li>
			<li class="category"><a href="/collections/outros"> <fmt:message key="navegacao.categoria.outros"/> </a></li>
		</ul>
	</nav>

src/main/webapp/WEB-INF/views/error.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %>

<tags:pageTemplate titulo="Produto não encontrado">

	<section id="index-section" class="container middle">
	
	<h2>${exeption.status} -  ${exception.message} !!!</h2>
	<!-- 
		mensagem: ${exception.message}
		<c:forEach items="${exception.stackTrace}" var="stk">
			${stk}
		</c:forEach>
	 -->

	</section>

</tags:pageTemplate>

src/main/webapp/WEB-INF/views/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security"%>

<%@ taglib tagdir="/WEB-INF/tags" prefix="tags" %>

<tags:pageTemplate titulo="Livros">

	<section id="index-section" class="container middle">
		<h1 class="cdc-call">Últimos dias com os preços promocionais. Aproveite!</h1>
		
		<ul class="clearfix book-collection">

			<c:forEach items="${produtos}" var="produto">
				<li>
					<a href="${s:mvcUrl('PC#detalhe').arg(0, produto.id).build()}" class="block clearfix">
					<h2 class="product-title">${produto.titulo}</h2> 
					<img width="143" height="202" src="https://cdn.shopify.com/s/files/1/0155/7645/products/java8-featured_large.png?v=1411490181" alt="Java 8 Prático" title="Java 8 Prático" /> 
					<small class="buy-button">Compre</small>
					</a>
				</li>
			</c:forEach>

		</ul>

		<h2 class="cdc-call">Diferenciais da Casa do Código</h2>

		<ul id="cdc-diferenciais" class="clearfix">
			<li class="col-left">
				<h3>E-books sem DRM. Leia onde quiser</h3>
				<p>
					<span class="sprite" id="sprite-drm"></span> Nossos e-books não possuem DRM, ou seja, você pode ler em qualquer computador, tablet e smartphone.
				</p>
			</li>
			<li class="col-right">
				<h3>Autores de renome na comunidade</h3>
				<p>
					<span class="sprite" id="sprite-renome"></span> Autores que participam ativamente na comunidade com Open Source, listas de discussão, grupos e
					mais.
				</p>
			</li>
			<li class="col-left">
				<h3>Receba atualizações dos e-books</h3>
				<p>
					<span class="sprite" id="sprite-atualizacoes"></span> Quando você compra um e-book, automaticamente tem direito às atualizações e correções dele.
				</p>
			</li>
			<li class="col-right">
				<h3>Livros com curadoria da Caelum</h3>
				<p>
					<span class="sprite" id="sprite-caelum"></span> Desenvolvedores experientes que avaliam e revisam os livros constantemente.
				</p>
			</li>
		</ul>



	</section>

</tags:pageTemplate>

src/main/webapp/WEB-INF/views/loginForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<c:url value="/resources/" var="cssPath" />
<link rel="stylesheet" type="text/css" media="all"
	href="${cssPath}css/bootstrap.min.css">
<script type="text/javascript" src="${cssPath}js/jquery.min.js"></script>
<script type="text/javascript" src="${cssPath}js/bootstrap.min.js"></script>
<title>livros de java</title>
</head>
<body>
	
	<div class="container p-5">
	<h1> Login da casa do codigo</h1>
		<form:form  servletRelativeAction="/login" method="post">
			<div class="form-group">
				<label>E-mail</label>
				<input name="username" type="text" class="form-control"/>
				
			</div>
			<div class="form-group">
				<label>Senha</label>
				<input name="password" type="password" Class="form-control"/>
			
			</div>
		

			<button type="submit" class="btn btn-success p-4">Logar</button>

		</form:form>
	</div>
</body>
</html>